### ISSUE TITLE
Responsive problem in landing page

### ISSUE THREAD

**Issue by binhtran432k** [hudy9x/namviek#249]
**Describe the bug**
The responsive may not be the main features of this project, but as a user for a first time opening a landing page in mobile devices this is very terrible.

**To Reproduce**
1. Go to <https://www.namviek.com> with mobiles size
2. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/694efafb-66b0-4f6c-a997-f0dcff71d644)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Edge
 - Version Latest

**Additional context**
This problem is a very simple, if you do not have time, I can open a PR to resolve this.

**Comment by hudy9x** [comment]
@binhtran432k thank for your feedback
But let's me clarify something first

I do know the mobile issue, because I choose to support only Desktop first
Because I have limited effort to do it that time. So it's not perfect.

> This problem is a very simple, if you do not have time, I can open a PR to resolve this.

Many one of you suggest me to contribute to correct it
But the landing page is not simple. It's the hardest thing i promise

And I've been planning to done it for few months to publish the app to some directories
So, for me, the landing page is important.

If you're still want to contribute to it, please give me some demos first

**Comment by binhtran432k** [comment]
Duplicate with hudy9x/namviek-landingpage/issues/6
